[inputs."assets/images/ui/glyphs/AD.png"]
hash = "55aff16f6d9bf9c81f07c571d2e3256fe4aca7b73e328ee97540fef5baf233ec"
id = 17150930576
packable = false

[inputs."assets/images/ui/glyphs/CD.png"]
hash = "3f9aa94f20fa20a5262a1e9997c9dab793e31435383dd30af387e0da8157855a"
id = 17150930719
packable = false

[inputs."assets/images/ui/glyphs/CDhovered.png"]
hash = "00101c0dfc7888440a15b2afeeb077e2c26647dbf900bb29a5db1795985f124c"
id = 17153336526
packable = false

[inputs."assets/images/ui/glyphs/CDselected.png"]
hash = "ec52ffb0adc9cd4914e04356ea0c44feb1a0667c98f8c65bf241fe87ce4401c2"
id = 17153336637
packable = false

[inputs."assets/images/ui/glyphs/CI.png"]
hash = "c2dda80029542c63493d4a7e0b5f6d6005383880529a4ecb392927dcfd66204e"
id = 17150930892
packable = false

[inputs."assets/images/ui/glyphs/DEA.png"]
hash = "12a97398461234feb3d71a970035739b4f116620c918a5090ddc768941902b39"
id = 17150931024
packable = false

[inputs."assets/images/ui/glyphs/E&T.png"]
hash = "9e23ca7c330f48d6431b864caadca875e4646f15ad693ae70a34f70ed57b7259"
id = 17150931129
packable = false

[inputs."assets/images/ui/glyphs/E&Thovered.png"]
hash = "6975bd8d43a485de5df76da5a7e4120917aaf558d88b9c9a72e0e7a1e94b1272"
id = 17153336754
packable = false

[inputs."assets/images/ui/glyphs/E&Tselected.png"]
hash = "c292cc9111d495c8b11148e2919024f9faff6241925bdf95ca5bdb8d475ce2a4"
id = 17153336850
packable = false

[inputs."assets/images/ui/glyphs/EC.png"]
hash = "14e1565689c68160639a037b184953c05a6a7c99e02b02ab18b68530c1c874c8"
id = 17150931238
packable = false

[inputs."assets/images/ui/glyphs/FP.png"]
hash = "d7ce3d581651fd88cda9576b8ab7f5356059344edad561fdb1ffdbff8971447c"
id = 17150931360
packable = false

[inputs."assets/images/ui/glyphs/FPhovered.png"]
hash = "214aad4382088dcd82f838d5f61973d83a0ba0e20242705dae232579117986fb"
id = 17153337034
packable = false

[inputs."assets/images/ui/glyphs/FPselected.png"]
hash = "e3985f04f4f58dccd11a91495a75c28e66a5c8e38530cb794bb4b8a7391cb676"
id = 17153337264
packable = false

[inputs."assets/images/ui/glyphs/LD.png"]
hash = "a40277a29660be29078ee112872d9ef7952029569f0c4d3ccddd26d40d31f39b"
id = 17150931516
packable = false

[inputs."assets/images/ui/glyphs/LDhovered.png"]
hash = "4f396ddb47abe6b7bb43193baa06129ac00a8fe04e9b1c9411f3796618c7e2f8"
id = 17153337483
packable = false

[inputs."assets/images/ui/glyphs/LDselected.png"]
hash = "23529bdb64a45764ddcba807ac2de37df5fb3d68f67fee572464334f7c0aba08"
id = 17153337614
packable = false

[inputs."assets/images/ui/glyphs/MAND.png"]
hash = "6c287ac13ff0e3e7de6ad2141ec0c42cd243c1a37dbbc1e7744c7dcb281d8d3f"
id = 17150931635
packable = false

[inputs."assets/images/ui/glyphs/MD.png"]
hash = "8ef39ff4e1e00e34173aa50de842ccce22841f209fdb10e15e72909859c06d6c"
id = 17150931771
packable = false

[inputs."assets/images/ui/glyphs/MDhovered.png"]
hash = "450d4716facf46d4c3ad761d798e6666e73b6b66ec11f2cb11a380fc86f28ea2"
id = 17153337743
packable = false

[inputs."assets/images/ui/glyphs/MDselected.png"]
hash = "3f7daa783faae0800525afba192338b53391c59603b13f0ed3207a6d44d474b4"
id = 17153337843
packable = false

[inputs."assets/images/ui/glyphs/MTF.png"]
hash = "988e8e5b9d9fd75a3b4230b5432a122f5cde19d928811968f409321df87f7754"
id = 17150931902
packable = false

[inputs."assets/images/ui/glyphs/SCD.png"]
hash = "e3f6c110aacb0d3c087a94289a8d4e7a018ed39a633e1384ad741e055445c580"
id = 17150932092
packable = false

[inputs."assets/images/ui/glyphs/SCDhovered.png"]
hash = "8e30933328be19f68608c100c108ccd9dafc2e3b59dba7e3d723377f9144d348"
id = 17153337924
packable = false

[inputs."assets/images/ui/glyphs/SCDselected.png"]
hash = "e65591d5fca05f552ee73c10c1090b97b83d5f35bed6f4495f9f22723285ef1c"
id = 17153338058
packable = false

[inputs."assets/images/ui/glyphs/SD.png"]
hash = "8dddbf745ba0dbe012f7ff2641f56ab0be263da709228bd713abfc977f5eadb2"
id = 17150932255
packable = false

[inputs."assets/images/ui/glyphs/SDhovered.png"]
hash = "d566c53acadf255e91e883c13b640649366a4ea8b152719f4299879e0bfd1f1a"
id = 17153338192
packable = false

[inputs."assets/images/ui/glyphs/SDselected.png"]
hash = "eb24f3726f91f1f6827902df3c6f83bffa2bae84792297347c6c3e500a246db7"
id = 17153338314
packable = false

[inputs."assets/images/ui/icons/arrowright.png"]
hash = "dfdc6e8dcc7a9f876891e04dcdf84777ecb6f8da6cc6eb0a5e8f2c00eb9a414e"
id = 17175586944
packable = false

[inputs."assets/images/ui/icons/attachments.png"]
hash = "f59b3c70759f3fb97442fc0364955d718c5ffe9664cd2247084ba220561ab906"
id = 17329656359
packable = false

[inputs."assets/images/ui/icons/attachmentsselected.png"]
hash = "10d145f91bc158bbb251828c6c66b064418c280516be6f7140611b28bdd6692e"
id = 17175669380
packable = false

[inputs."assets/images/ui/icons/audio.png"]
hash = "a44bfafff67207fff1bd6618fb695eb4014c488b8740d549e7af6af8244772f0"
id = 17254582936
packable = false

[inputs."assets/images/ui/icons/character_customization_icons.png"]
hash = "100d593a753b747039d939fafcba90b09064b469cf118349146e553753b6e984"
id = 17329765274
packable = false

[inputs."assets/images/ui/icons/customize.png"]
hash = "d032a7f0f571db8236ba2f7d55d7e3fc170d94cb70ab8c7f189ceb26dec03ece"
id = 17151101784
packable = false

[inputs."assets/images/ui/icons/down.png"]
hash = "f0b663106b74d73fc616ea1a268b30a4ddbeba100dd39f40155103795e33bf85"
id = 17150932825
packable = false

[inputs."assets/images/ui/icons/downselected.png"]
hash = "de9564d54e922b0ecbf75946a7b4d6974a2b66378c0466b4ea8a18560c674816"
id = 17153427979
packable = false

[inputs."assets/images/ui/icons/downselectedcd.png"]
hash = "ce84c8c69bd613e711a56afe8f1d89c9a734052a5dc13e18209f6c47216d62f4"
id = 17153428318
packable = false

[inputs."assets/images/ui/icons/downselectedwhite.png"]
hash = "f1ef2b519f1cf49bde14d42e1fb10a3f6adb037c0ab78ee6aa7ac2591edd72ce"
id = 17798339306
packable = false

[inputs."assets/images/ui/icons/edit.png"]
hash = "25497c4ad785523237e7cdecb1d9d999e6d3bfd3aa5e7829933f68e10fca0e2a"
id = 17276434560
packable = false

[inputs."assets/images/ui/icons/group.png"]
hash = "a25f1bc9fe042830dac7ba5ae5df47fd60c6db873235ba82931faa4ad0b098e3"
id = 17329656663
packable = false

[inputs."assets/images/ui/icons/groupselected.png"]
hash = "ba91f4de2b81226c19906e64efcf2b62fb70999f240a1fcda7c8ee7a385fdf17"
id = 17151058415
packable = false

[inputs."assets/images/ui/icons/handgun.png"]
hash = "1ed5e4d90a9d643980eb57f68990704864b793fbfffc7bcd19803b44d9c6a8cd"
id = 17329656884
packable = false

[inputs."assets/images/ui/icons/handgunselected.png"]
hash = "a4a3a672e3f1680f37308451d99bf7b66c258a9c8c61d8b325db40ff07fcf526"
id = 17151020582
packable = false

[inputs."assets/images/ui/icons/home.png"]
hash = "2908199de4458099532ec089e621cf943a38f7c7316fc358a15ee2415c6be9a2"
id = 17254583151
packable = false

[inputs."assets/images/ui/icons/knife.png"]
hash = "e02f00c3ad5242c9729f78be4cf9d1375908d4a1691879380d421bcc06d572c0"
id = 17329656988
packable = false

[inputs."assets/images/ui/icons/knifeselected.png"]
hash = "df3ce5936d506afbc581c88c17c46e32fb35f126f174a1262d805a50977075ea"
id = 17151020876
packable = false

[inputs."assets/images/ui/icons/notification.png"]
hash = "30fa6635e4a3b3393df001a0a76d3a2e5e1d99deccd235c308f8b32950e6d4c5"
id = 17276434629
packable = false

[inputs."assets/images/ui/icons/os_icons.png"]
hash = "58381dfd2100d9af9363e1726979dab9857a838f0cd4c36b2585e5043b1550b3"
id = 17254583284
packable = false

[inputs."assets/images/ui/icons/pencil.png"]
hash = "c31bc00ccb1058fffb151007ecfbc8e3b04ce1f1dcf9639f430862023f549cbf"
id = 17329657107
packable = false

[inputs."assets/images/ui/icons/pencilselected.png"]
hash = "ac1c79699aca245daab72c38ecebb432eeb9d45b9b2f09ae811cf5f957902b4f"
id = 17151058737
packable = false

[inputs."assets/images/ui/icons/power.png"]
hash = "aa081104a20a2be3c60fdbdf662cf154569e03b1ad669f76586641bc3c1e0600"
id = 17254583437
packable = false

[inputs."assets/images/ui/icons/research.png"]
hash = "d5881fdaf2e37efb1aef0b3c83c9dd1bc3a5391acd1c77637d61dd025b7462f6"
id = 17254583568
packable = false

[inputs."assets/images/ui/icons/rifle.png"]
hash = "faac52e206730edd4845331402e46a4a5c5d7625ac76b9e4824c59a834d6b868"
id = 17329657343
packable = false

[inputs."assets/images/ui/icons/rifleselected.png"]
hash = "f3e09eca3cb8537ffe0b5930750bd44b0861dc0fa39e8660a8d2c12d67670ad4"
id = 17151021382
packable = false

[inputs."assets/images/ui/icons/scp_badge.png"]
hash = "ed1bfbe14008a34ae7313750f4abf6cf8967c25584cbd22c640e5e1177b2fcd9"
id = 17280979270
packable = false

[inputs."assets/images/ui/icons/scrollbarbot.png"]
hash = "a6eab2ab82a8220402ad6cdf8b1f604a8a4195156eb85f180733913126c62455"
id = 17264959824
packable = false

[inputs."assets/images/ui/icons/scrollbarmid.png"]
hash = "565ebf96e363a57a2395b836cbdc764ac49746ca51b2e7d4cb2a23ca15b5188f"
id = 17264959908
packable = false

[inputs."assets/images/ui/icons/scrollbartop.png"]
hash = "26a215caeca17c11072ed4042c99c298629b2e854e791639e10a967e24bc222b"
id = 17264960001
packable = false

[inputs."assets/images/ui/icons/shirt.png"]
hash = "a97cf1bd8fa3f93f19fb752d3152da00bc4d8a00f4e421a094f7db4fdf116e03"
id = 17329657486
packable = false

[inputs."assets/images/ui/icons/shirtselected.png"]
hash = "87da3a2068ae2cce7b6df1e28d405691107852ed54335c48c3ff713928a5d56b"
id = 17151058995
packable = false

[inputs."assets/images/ui/icons/toparrow.png"]
hash = "5cf3119a81574ae61d1af73644c2b6904ac05fbea4c8cd28e8a1db3e1f49459d"
id = 17151059058
packable = false

[inputs."assets/images/ui/icons/trash.png"]
hash = "173fd2aa9fe9b954813a4bd449714337a01913f69b561dc794348383432ea7cd"
id = 17276434718
packable = false

[inputs."assets/images/ui/icons/vest.png"]
hash = "7568cc238528db025798a60dc17f4a4586bbd11e2fbcdfa482a0510bfd6435d2"
id = 17329657576
packable = false

[inputs."assets/images/ui/icons/weapon_customization_icons.png"]
hash = "794023da758a379c5923855bca5a337f606b261e138194f52f8d9484f6e9af58"
id = 17329765478
packable = false

[inputs."assets/images/ui/icons/weapon_customize.png"]
hash = "221f88ea40a129044b60531810e1becf37c1a1e8c34f525bf591ef77cdb96eea"
id = 17337522724
packable = false

[inputs."assets/images/ui/misc/close.png"]
hash = "2195dfcbcc783d590825b98aa6390fffe48efd1509a6a3414677d3d3fe2fc86a"
id = 17251632751
packable = false

[inputs."assets/images/ui/misc/divider.png"]
hash = "2e1871aeeacebc75cbb5be93ca6001a8c83526ac7cadb79206e1889cd850e9bb"
id = 17151021776
packable = false

[inputs."assets/images/ui/misc/foundationlogo.png"]
hash = "ed7acfebe6b5a955cbe3c5a9dd8d3c6775844d788c1b754cfbe9e6936561f0a3"
id = 17153143297
packable = false

[inputs."assets/images/ui/misc/objectivemarker.png"]
hash = "d82a2ce870116a8375f059e5d63943968e09b400b246018f164b51842c219827"
id = 17249239160
packable = false

[inputs."assets/images/ui/misc/selectionbackground.png"]
hash = "669dae135d7e75bd5f6bf245fc23efe22e28db929aa1eb3b05260b2a51dd8b68"
id = 17785115600
packable = false

[inputs."assets/images/ui/misc/vignette.png"]
hash = "81bdbc8b86fea75db5c77a898552967f1c9dc7f0d99dda31b7e4dc9361f347f2"
id = 17159843312
packable = false
